### ISSUE TITLE
[Feature Request] Is it possible to add a setting to fix the drift in China?

### ISSUE THREAD

**Issue by GhostFlying** [veikus/ingresshelper#3]
Due to some xxx reasons, using the default Google Maps layer in China may have some drifts, the transform between the two coordinate can be found in this : https://github.com/googollee/eviltransform

As a player in China, I wish the bot can fix the drift automatically, is this possible?

**Comment by veikus** [comment]
@GhostFlying hi, i know about problem. I released new version with ability to set iitc plugins. "Fix Google Map offset in China" is also available. Hope it will help for a first time.

P.S. I'm going to integrate plugin you found in further versions. Thank you.
